# This file contains values from Cookiecutter

default_context:
  project_name: "wearipedia"
  project_description: "wearables in development"
  organization: "Rodrigo Castellon"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "rodrigo-castellon"
  email: "rjcaste@stanford.edu"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
